### ISSUE TITLE
Automatische Synchronisierung via. Casagateway

### ISSUE THREAD

**Issue by timportner-pp** [CasasoftCH/casawp#14]
Aktuell kann man den Import nur manuell ausführen (korrigiert mich gerne). Wir haben uns daher mit folgenden Code beholfen, welcher einmal stündlich den Import ausführt. Evtl. wäre das eine Funktionalität für das Plugin.

add_action('wp', function(){
  if (! wp_next_scheduled ( 'pp_sync_casagateway' )) {
		wp_schedule_event(time(), 'hourly', 'pp_sync_casagateway');
  }
});

add_action('pp_sync_casagateway', function () {
	$import = new casawp\Import(false, true);
	$import->addToLog('Update from casagateway caused import');
});

**Comment by jensstalder** [comment]
Entschulde habe diese Nachricht nicht gesehen.

Eigentlich kann man auf dem Gateway ein sogenante Hook/Poke url hinterlegen der bei jeglicher Änderung die url automatisch anstosst. Mit einem Cron würde man unnötig trafic verursachen.

Um Welche Webseite handelt es sich? Dann können wir dies gleich einrichten/überprüfen.
