### ISSUE TITLE
WPML + CASAWP = nicht kompatibel?

### ISSUE THREAD

**Issue by maucherOnline** [CasasoftCH/casawp#21]
Hi,

wir haben das Plugin mit WPML im Einsatz und haben massive Probleme mit den Ladezeiten.
Wenn englische Seiten aufgerufen werden, lädt die Seite teilweise 30 Sekunden. Bei DE ist alles in Ordnung.
Sobald man das Plugin deaktiviert, lädt wieder alles normal. 

Ich habe zunächst Zeile 18 bis 46 in der `casawp.php` auskommentiert. Aber das alleine scheint keinen Effekt zu haben.

Bei Casasoft sagte man uns, es gebe keinen Support (mehr?). Das Plugin wird aber scheinbar hier noch gepflegt - zumindest bis Mai 2020 sieht man noch commits.

Wie können wir hierzu Hilfestellung erhalten?

**Comment by DimitrijRees** [comment]
Guten Tag

Wir stellen das Plugin kostenfrei zur Verfügung und nutzen es jeweils auch immer selbst für eigene Entwicklungen, deshalb sehen Sie regelmässige Releases. Support bieten wir dafür aber nicht an, das Plugin muss vom jeweiligen Entwickler selbst ins WP integriert werden.

WPML nutzen wir jeweils auch immer für mehrsprachige Seiten und haben keine solche Probleme, von daher vermute ich im Theme selbst oder mit anderen Plugins einen Konflikt. Aufgrund der Komplexität von WPML ist das Konfliktpotential generell gross.

Besten Dank für Ihr Verständnis.
