### ISSUE TITLE
CASAWP + WPML: Bilder aus Casagateway werden bei EN nicht angezeigt

### ISSUE THREAD

**Issue by maucherOnline** [CasasoftCH/casawp#22]
Hi,

wir haben CASAWP und WPML im Einsatz. Da der Import von 11 Objekten in DE + EN immer abbricht, bzw. zum Server Error 500 führte, haben wir auf Bilder per CDN umgestellt. Das funktioniert zwar besser/schneller beim Import, dafür werden die Bilder bei der Detail View der EN Exposés nicht mehr ausgegeben. Es scheint hier die Verknüpfung zu fehlen, denn im HTML sieht man keinerlei `<img>` tags bei der Galerie.

**Comment by DimitrijRees** [comment]
Guten Tag

Diese Option wurde genau aus diesem Grund integriert, da Kill-Scripts der Server grössere Importe irgendwann abbrechen. Vor allem Bilder fallen beim Import ins Gewicht.

Auch hier können wir leider keine ähnlichen Erfahrungen mit Ihnen teilen, die Problematik ist uns nicht bekannt und stammt vermutlich von einem anderen Konflikt. Den CDN nutzen wir bei all unseren Seiten, die mehr als 10 Objekte importieren (das sind gegen 300-400 Webseiten, Bilder werden überall korrekt daregstellt).

Wie bereits gesagt bieten wir leider keinen Support für CASAWP an, das Plugin muss auf eigene Faust integriert werden.
