### ISSUE TITLE
Cannot modify header information - headers already sent by

### ISSUE THREAD

**Issue by PatrickMLS** [CasasoftCH/casawp#36]
Hello all

Unfortunately, I get an error message when overwriting the imported properties.

Warning: Cannot modify header information - headers already sent by (output started at /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-content/plugins/casawp/classes/Import.php:1225) in /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-includes/functions.php on line 6821 Warning: Cannot modify header information - headers already sent by (output started at /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-content/plugins/casawp/classes/Import.php:1225) in /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-admin/includes/misc.php on line 1310 Warning: Cannot modify header information - headers already sent by (output started at /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-content/plugins/casawp/classes/Import.php:1225) in /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-admin/admin-header.php on line 9 Warning: Cannot modify header information - headers already sent by (output started at /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-content/plugins/casawp/classes/Import.php:1225) in /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-includes/option.php on line 1109 Warning: Cannot modify header information - headers already sent by (output started at /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-content/plugins/casawp/classes/Import.php:1225) in /home/httpd/vhosts/mls-test.ch/vonrosenberg.mls-test.ch/wp-includes/option.php on line 1110

I have a default theme in use and otherwise no other plugins active. In addition, WordPress and also the PHP version are up to date.

What is the reason for this? Can anyone help me out with this?

Thanks and best regards

Patrick

**Comment by DimitrijRees** [comment]
Hello Patrick

Since this is only a warning and not an error, does the import itself work?

We cannot replicate this issue. Maybe it's related to your virtual host. Is the OS of your server up to date? There might be an issue with Let's Encrypt SSL while establishing the API connection to our Gateway (see 1st October 2021 global Let's Encrypt issue https://community.letsencrypt.org/t/hi-from-october-1st-2021-on-worlds-lets-encrypt-ssl-old-certificates-not-working-old-operating-systems-how-to-update-it/162316). If your OS is up to date this shouldn't be the issue.

Best
Dimitrij

**Comment by PatrickMLS** [comment]
Hello Dimitrij

Thanks for your reply.

Yes, the import itself is working.

What do you mean with OS? We have a normally webhosting and everything should be up to date.

Best regards

Patrick

**Comment by DimitrijRees** [comment]
Hello Patrick

I mean the operating system of the webserver you're using. In our experience with virtual hosts, there may be an SSL issue. There was a global Let's Encrypt issue on 1st October 2021, maybe your server needs an update.

The warning is being thrown on line 1225 in import.php of casawp. This line is only showing the transcript of the import via print_r function. Seems like this is being blocked on your vhost.

Maybe this also helps: https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php

Search for:
But it worked on the other server!?

If you didn't get the headers warning before, then the output buffering php.ini setting has changed. It's likely unconfigured on the current/new server.

--

As this seems to be a config issue on the web server I will close this ticket for now.

Best
Dimitrij

**Comment by PatrickMLS** [comment]
Hello Dimitrij

According to our hosting provider, the OS is up to date and the necessary updates regarding the SSL certificate were made on the same day as mentioned.

Have you any other ideas for this problem?

Best regards,

Patrick
