### ISSUE TITLE
$.jStorage is undefined

### ISSUE THREAD

**Issue by Gagi33** [CasasoftCH/casawp#50]
Hello,

Since I activated your plugin on a client's site, I have this javascript error:

$.jStorage is undefined

Can you help me?

With my best regards.
Gaël Rosset

**Comment by DimitrijRees** [comment]
Hello,

I have just tested it on a new WordPress installation with a WP default theme and CASAWP as only plugin. Unfortunately I can't replicate the issue. You can try to narrow the issue down by disabling other plugins - or search for possible conflicts within your theme.

Going to close this issue for now.
